//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ethos/elint/services/product/knowledge/space_knowledge/create_space_knowledge.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeServiceClient`, then call methods of this protocol to make API calls.
internal protocol Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeServiceClientInterceptorFactoryProtocol? { get }

  func createSpaceKnowledge(
    _ request: Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeRequest, Elint_Entity_Space>
}

extension Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeServiceClientProtocol {
  internal var serviceName: String {
    return "elint.services.product.knowledge.space.CreateSpaceKnowledgeService"
  }

  /// Unary call to CreateSpaceKnowledge
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateSpaceKnowledge.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createSpaceKnowledge(
    _ request: Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeRequest, Elint_Entity_Space> {
    return self.makeUnaryCall(
      path: "/elint.services.product.knowledge.space.CreateSpaceKnowledgeService/CreateSpaceKnowledge",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSpaceKnowledgeInterceptors() ?? []
    )
  }
}

internal protocol Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'createSpaceKnowledge'.
  func makeCreateSpaceKnowledgeInterceptors() -> [ClientInterceptor<Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeRequest, Elint_Entity_Space>]
}

internal final class Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeServiceClient: Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the elint.services.product.knowledge.space.CreateSpaceKnowledgeService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

