// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ethos/elint/services/product/knowledge/space_knowledge/create_space_knowledge.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Auth Properties
  var spaceDetails: Elint_Entity_Space {
    get {return _storage._spaceDetails ?? Elint_Entity_Space()}
    set {_uniqueStorage()._spaceDetails = newValue}
  }
  /// Returns true if `spaceDetails` has been explicitly set.
  var hasSpaceDetails: Bool {return _storage._spaceDetails != nil}
  /// Clears the value of `spaceDetails`. Subsequent reads from it will return its default value.
  mutating func clearSpaceDetails() {_uniqueStorage()._spaceDetails = nil}

  var spaceKnowledgeAccessSessionTokenDetails: Elint_Entity_PersistentSessionTokenDetails {
    get {return _storage._spaceKnowledgeAccessSessionTokenDetails ?? Elint_Entity_PersistentSessionTokenDetails()}
    set {_uniqueStorage()._spaceKnowledgeAccessSessionTokenDetails = newValue}
  }
  /// Returns true if `spaceKnowledgeAccessSessionTokenDetails` has been explicitly set.
  var hasSpaceKnowledgeAccessSessionTokenDetails: Bool {return _storage._spaceKnowledgeAccessSessionTokenDetails != nil}
  /// Clears the value of `spaceKnowledgeAccessSessionTokenDetails`. Subsequent reads from it will return its default value.
  mutating func clearSpaceKnowledgeAccessSessionTokenDetails() {_uniqueStorage()._spaceKnowledgeAccessSessionTokenDetails = nil}

  /// Create Properties
  var spaceType: Elint_Entity_SpaceType {
    get {return _storage._spaceType}
    set {_uniqueStorage()._spaceType = newValue}
  }

  var spaceIsolationType: Elint_Entity_SpaceIsolationType {
    get {return _storage._spaceIsolationType}
    set {_uniqueStorage()._spaceIsolationType = newValue}
  }

  var galaxy: Elint_Entity_Galaxy {
    get {return _storage._galaxy ?? Elint_Entity_Galaxy()}
    set {_uniqueStorage()._galaxy = newValue}
  }
  /// Returns true if `galaxy` has been explicitly set.
  var hasGalaxy: Bool {return _storage._galaxy != nil}
  /// Clears the value of `galaxy`. Subsequent reads from it will return its default value.
  mutating func clearGalaxy() {_uniqueStorage()._galaxy = nil}

  /// Meta Properties
  var requestedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._requestedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._requestedAt = newValue}
  }
  /// Returns true if `requestedAt` has been explicitly set.
  var hasRequestedAt: Bool {return _storage._requestedAt != nil}
  /// Clears the value of `requestedAt`. Subsequent reads from it will return its default value.
  mutating func clearRequestedAt() {_uniqueStorage()._requestedAt = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "elint.services.product.knowledge.space"

extension Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateSpaceKnowledgeRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "space_details"),
    2: .standard(proto: "space_knowledge_access_session_token_details"),
    3: .standard(proto: "space_type"),
    4: .standard(proto: "space_isolation_type"),
    5: .same(proto: "galaxy"),
    6: .standard(proto: "requested_at"),
  ]

  fileprivate class _StorageClass {
    var _spaceDetails: Elint_Entity_Space? = nil
    var _spaceKnowledgeAccessSessionTokenDetails: Elint_Entity_PersistentSessionTokenDetails? = nil
    var _spaceType: Elint_Entity_SpaceType = .closed
    var _spaceIsolationType: Elint_Entity_SpaceIsolationType = .notIsolated
    var _galaxy: Elint_Entity_Galaxy? = nil
    var _requestedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _spaceDetails = source._spaceDetails
      _spaceKnowledgeAccessSessionTokenDetails = source._spaceKnowledgeAccessSessionTokenDetails
      _spaceType = source._spaceType
      _spaceIsolationType = source._spaceIsolationType
      _galaxy = source._galaxy
      _requestedAt = source._requestedAt
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._spaceDetails) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._spaceKnowledgeAccessSessionTokenDetails) }()
        case 3: try { try decoder.decodeSingularEnumField(value: &_storage._spaceType) }()
        case 4: try { try decoder.decodeSingularEnumField(value: &_storage._spaceIsolationType) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._galaxy) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._requestedAt) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._spaceDetails {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if let v = _storage._spaceKnowledgeAccessSessionTokenDetails {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if _storage._spaceType != .closed {
        try visitor.visitSingularEnumField(value: _storage._spaceType, fieldNumber: 3)
      }
      if _storage._spaceIsolationType != .notIsolated {
        try visitor.visitSingularEnumField(value: _storage._spaceIsolationType, fieldNumber: 4)
      }
      if let v = _storage._galaxy {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
      if let v = _storage._requestedAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeRequest, rhs: Elint_Services_Product_Knowledge_Space_CreateSpaceKnowledgeRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._spaceDetails != rhs_storage._spaceDetails {return false}
        if _storage._spaceKnowledgeAccessSessionTokenDetails != rhs_storage._spaceKnowledgeAccessSessionTokenDetails {return false}
        if _storage._spaceType != rhs_storage._spaceType {return false}
        if _storage._spaceIsolationType != rhs_storage._spaceIsolationType {return false}
        if _storage._galaxy != rhs_storage._galaxy {return false}
        if _storage._requestedAt != rhs_storage._requestedAt {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
