//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ethos/elint/services/product/knowledge/space_knowledge_domain/create_space_knowledge_domain.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainServiceClient`, then call methods of this protocol to make API calls.
internal protocol Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainServiceClientInterceptorFactoryProtocol? { get }

  func createSpaceKnowledgeDomain(
    _ request: Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainRequest, Elint_Entity_SpaceKnowledgeDomain>
}

extension Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainServiceClientProtocol {
  internal var serviceName: String {
    return "elint.services.product.knowledge.domain.CreateSpaceKnowledgeDomainService"
  }

  /// Unary call to CreateSpaceKnowledgeDomain
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateSpaceKnowledgeDomain.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createSpaceKnowledgeDomain(
    _ request: Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainRequest, Elint_Entity_SpaceKnowledgeDomain> {
    return self.makeUnaryCall(
      path: "/elint.services.product.knowledge.domain.CreateSpaceKnowledgeDomainService/CreateSpaceKnowledgeDomain",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSpaceKnowledgeDomainInterceptors() ?? []
    )
  }
}

internal protocol Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'createSpaceKnowledgeDomain'.
  func makeCreateSpaceKnowledgeDomainInterceptors() -> [ClientInterceptor<Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainRequest, Elint_Entity_SpaceKnowledgeDomain>]
}

internal final class Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainServiceClient: Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the elint.services.product.knowledge.domain.CreateSpaceKnowledgeDomainService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Elint_Services_Product_Knowledge_Domain_CreateSpaceKnowledgeDomainServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

