// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ethos/elint/services/product/identity/account/create_account.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Elint_Services_Product_Identity_Account_ValidateAccountWithMobileRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Service Request Properties
  var accountMobileNumber: String = String()

  /// Meta Properties
  var requestedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _requestedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_requestedAt = newValue}
  }
  /// Returns true if `requestedAt` has been explicitly set.
  var hasRequestedAt: Bool {return self._requestedAt != nil}
  /// Clears the value of `requestedAt`. Subsequent reads from it will return its default value.
  mutating func clearRequestedAt() {self._requestedAt = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _requestedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

struct Elint_Services_Product_Identity_Account_ValidateAccountWithMobileResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Auth Properties
  var accountCreationAuthDetails: Elint_Services_Product_Identity_Account_AccountCreationAuthDetails {
    get {return _storage._accountCreationAuthDetails ?? Elint_Services_Product_Identity_Account_AccountCreationAuthDetails()}
    set {_uniqueStorage()._accountCreationAuthDetails = newValue}
  }
  /// Returns true if `accountCreationAuthDetails` has been explicitly set.
  var hasAccountCreationAuthDetails: Bool {return _storage._accountCreationAuthDetails != nil}
  /// Clears the value of `accountCreationAuthDetails`. Subsequent reads from it will return its default value.
  mutating func clearAccountCreationAuthDetails() {_uniqueStorage()._accountCreationAuthDetails = nil}

  /// Service Response Properties
  var accountExistsWithMobile: Bool {
    get {return _storage._accountExistsWithMobile}
    set {_uniqueStorage()._accountExistsWithMobile = newValue}
  }

  var verificationCodeTokenDetails: Elint_Entity_TemporaryTokenDetails {
    get {return _storage._verificationCodeTokenDetails ?? Elint_Entity_TemporaryTokenDetails()}
    set {_uniqueStorage()._verificationCodeTokenDetails = newValue}
  }
  /// Returns true if `verificationCodeTokenDetails` has been explicitly set.
  var hasVerificationCodeTokenDetails: Bool {return _storage._verificationCodeTokenDetails != nil}
  /// Clears the value of `verificationCodeTokenDetails`. Subsequent reads from it will return its default value.
  mutating func clearVerificationCodeTokenDetails() {_uniqueStorage()._verificationCodeTokenDetails = nil}

  var codeSentAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._codeSentAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._codeSentAt = newValue}
  }
  /// Returns true if `codeSentAt` has been explicitly set.
  var hasCodeSentAt: Bool {return _storage._codeSentAt != nil}
  /// Clears the value of `codeSentAt`. Subsequent reads from it will return its default value.
  mutating func clearCodeSentAt() {_uniqueStorage()._codeSentAt = nil}

  /// Meta Properties
  var validateAccountWithMobileDone: Bool {
    get {return _storage._validateAccountWithMobileDone}
    set {_uniqueStorage()._validateAccountWithMobileDone = newValue}
  }

  var validateAccountWithMobileMessage: String {
    get {return _storage._validateAccountWithMobileMessage}
    set {_uniqueStorage()._validateAccountWithMobileMessage = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Elint_Services_Product_Identity_Account_VerificationAccountRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Auth Properties
  var accountCreationAuthDetails: Elint_Services_Product_Identity_Account_AccountCreationAuthDetails {
    get {return _storage._accountCreationAuthDetails ?? Elint_Services_Product_Identity_Account_AccountCreationAuthDetails()}
    set {_uniqueStorage()._accountCreationAuthDetails = newValue}
  }
  /// Returns true if `accountCreationAuthDetails` has been explicitly set.
  var hasAccountCreationAuthDetails: Bool {return _storage._accountCreationAuthDetails != nil}
  /// Clears the value of `accountCreationAuthDetails`. Subsequent reads from it will return its default value.
  mutating func clearAccountCreationAuthDetails() {_uniqueStorage()._accountCreationAuthDetails = nil}

  /// Service Request Properties
  var resendCode: Bool {
    get {return _storage._resendCode}
    set {_uniqueStorage()._resendCode = newValue}
  }

  var verificationCode: String {
    get {return _storage._verificationCode}
    set {_uniqueStorage()._verificationCode = newValue}
  }

  var verificationCodeTokenDetails: Elint_Entity_TemporaryTokenDetails {
    get {return _storage._verificationCodeTokenDetails ?? Elint_Entity_TemporaryTokenDetails()}
    set {_uniqueStorage()._verificationCodeTokenDetails = newValue}
  }
  /// Returns true if `verificationCodeTokenDetails` has been explicitly set.
  var hasVerificationCodeTokenDetails: Bool {return _storage._verificationCodeTokenDetails != nil}
  /// Clears the value of `verificationCodeTokenDetails`. Subsequent reads from it will return its default value.
  mutating func clearVerificationCodeTokenDetails() {_uniqueStorage()._verificationCodeTokenDetails = nil}

  /// Meta Properties
  var requestedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._requestedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._requestedAt = newValue}
  }
  /// Returns true if `requestedAt` has been explicitly set.
  var hasRequestedAt: Bool {return _storage._requestedAt != nil}
  /// Clears the value of `requestedAt`. Subsequent reads from it will return its default value.
  mutating func clearRequestedAt() {_uniqueStorage()._requestedAt = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Elint_Services_Product_Identity_Account_VerificationAccountResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Meta Properties
  var verificationDone: Bool = false

  var verificationMessage: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Elint_Services_Product_Identity_Account_CaptureAccountMetaDetailsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Auth Properties
  var accountCreationAuthDetails: Elint_Services_Product_Identity_Account_AccountCreationAuthDetails {
    get {return _storage._accountCreationAuthDetails ?? Elint_Services_Product_Identity_Account_AccountCreationAuthDetails()}
    set {_uniqueStorage()._accountCreationAuthDetails = newValue}
  }
  /// Returns true if `accountCreationAuthDetails` has been explicitly set.
  var hasAccountCreationAuthDetails: Bool {return _storage._accountCreationAuthDetails != nil}
  /// Clears the value of `accountCreationAuthDetails`. Subsequent reads from it will return its default value.
  mutating func clearAccountCreationAuthDetails() {_uniqueStorage()._accountCreationAuthDetails = nil}

  /// Service Request Properties
  var accountFirstName: String {
    get {return _storage._accountFirstName}
    set {_uniqueStorage()._accountFirstName = newValue}
  }

  var accountLastName: String {
    get {return _storage._accountLastName}
    set {_uniqueStorage()._accountLastName = newValue}
  }

  var accountBirthAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._accountBirthAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._accountBirthAt = newValue}
  }
  /// Returns true if `accountBirthAt` has been explicitly set.
  var hasAccountBirthAt: Bool {return _storage._accountBirthAt != nil}
  /// Clears the value of `accountBirthAt`. Subsequent reads from it will return its default value.
  mutating func clearAccountBirthAt() {_uniqueStorage()._accountBirthAt = nil}

  var accountGender: Elint_Entity_AccountGender {
    get {return _storage._accountGender}
    set {_uniqueStorage()._accountGender = newValue}
  }

  /// Meta Properties
  var requestedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._requestedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._requestedAt = newValue}
  }
  /// Returns true if `requestedAt` has been explicitly set.
  var hasRequestedAt: Bool {return _storage._requestedAt != nil}
  /// Clears the value of `requestedAt`. Subsequent reads from it will return its default value.
  mutating func clearRequestedAt() {_uniqueStorage()._requestedAt = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Elint_Services_Product_Identity_Account_CaptureAccountMetaDetailsResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Service Response Properties
  var accountServiceAccessAuthDetails: Elint_Services_Product_Identity_Account_AccountServicesAccessAuthDetails {
    get {return _accountServiceAccessAuthDetails ?? Elint_Services_Product_Identity_Account_AccountServicesAccessAuthDetails()}
    set {_accountServiceAccessAuthDetails = newValue}
  }
  /// Returns true if `accountServiceAccessAuthDetails` has been explicitly set.
  var hasAccountServiceAccessAuthDetails: Bool {return self._accountServiceAccessAuthDetails != nil}
  /// Clears the value of `accountServiceAccessAuthDetails`. Subsequent reads from it will return its default value.
  mutating func clearAccountServiceAccessAuthDetails() {self._accountServiceAccessAuthDetails = nil}

  /// Meta Properties
  var accountCreationDone: Bool = false

  var accountCreationMessage: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _accountServiceAccessAuthDetails: Elint_Services_Product_Identity_Account_AccountServicesAccessAuthDetails? = nil
}

struct Elint_Services_Product_Identity_Account_AccountCreationAuthDetails {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Auth Properties
  var accountMobileNumber: String = String()

  /// What is the session token wrt this request?
  var accountCreationSessionTokenDetails: Elint_Entity_PersistentSessionTokenDetails {
    get {return _accountCreationSessionTokenDetails ?? Elint_Entity_PersistentSessionTokenDetails()}
    set {_accountCreationSessionTokenDetails = newValue}
  }
  /// Returns true if `accountCreationSessionTokenDetails` has been explicitly set.
  var hasAccountCreationSessionTokenDetails: Bool {return self._accountCreationSessionTokenDetails != nil}
  /// Clears the value of `accountCreationSessionTokenDetails`. Subsequent reads from it will return its default value.
  mutating func clearAccountCreationSessionTokenDetails() {self._accountCreationSessionTokenDetails = nil}

  /// Meta Properties
  var requestedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _requestedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_requestedAt = newValue}
  }
  /// Returns true if `requestedAt` has been explicitly set.
  var hasRequestedAt: Bool {return self._requestedAt != nil}
  /// Clears the value of `requestedAt`. Subsequent reads from it will return its default value.
  mutating func clearRequestedAt() {self._requestedAt = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _accountCreationSessionTokenDetails: Elint_Entity_PersistentSessionTokenDetails? = nil
  fileprivate var _requestedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "elint.services.product.identity.account"

extension Elint_Services_Product_Identity_Account_ValidateAccountWithMobileRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ValidateAccountWithMobileRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "account_mobile_number"),
    2: .standard(proto: "requested_at"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.accountMobileNumber) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._requestedAt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.accountMobileNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.accountMobileNumber, fieldNumber: 1)
    }
    if let v = self._requestedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Identity_Account_ValidateAccountWithMobileRequest, rhs: Elint_Services_Product_Identity_Account_ValidateAccountWithMobileRequest) -> Bool {
    if lhs.accountMobileNumber != rhs.accountMobileNumber {return false}
    if lhs._requestedAt != rhs._requestedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Elint_Services_Product_Identity_Account_ValidateAccountWithMobileResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ValidateAccountWithMobileResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "account_creation_auth_details"),
    2: .standard(proto: "account_exists_with_mobile"),
    3: .standard(proto: "verification_code_token_details"),
    4: .standard(proto: "code_sent_at"),
    5: .standard(proto: "validate_account_with_mobile_done"),
    6: .standard(proto: "validate_account_with_mobile_message"),
  ]

  fileprivate class _StorageClass {
    var _accountCreationAuthDetails: Elint_Services_Product_Identity_Account_AccountCreationAuthDetails? = nil
    var _accountExistsWithMobile: Bool = false
    var _verificationCodeTokenDetails: Elint_Entity_TemporaryTokenDetails? = nil
    var _codeSentAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _validateAccountWithMobileDone: Bool = false
    var _validateAccountWithMobileMessage: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _accountCreationAuthDetails = source._accountCreationAuthDetails
      _accountExistsWithMobile = source._accountExistsWithMobile
      _verificationCodeTokenDetails = source._verificationCodeTokenDetails
      _codeSentAt = source._codeSentAt
      _validateAccountWithMobileDone = source._validateAccountWithMobileDone
      _validateAccountWithMobileMessage = source._validateAccountWithMobileMessage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._accountCreationAuthDetails) }()
        case 2: try { try decoder.decodeSingularBoolField(value: &_storage._accountExistsWithMobile) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._verificationCodeTokenDetails) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._codeSentAt) }()
        case 5: try { try decoder.decodeSingularBoolField(value: &_storage._validateAccountWithMobileDone) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._validateAccountWithMobileMessage) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._accountCreationAuthDetails {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._accountExistsWithMobile != false {
        try visitor.visitSingularBoolField(value: _storage._accountExistsWithMobile, fieldNumber: 2)
      }
      if let v = _storage._verificationCodeTokenDetails {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if let v = _storage._codeSentAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if _storage._validateAccountWithMobileDone != false {
        try visitor.visitSingularBoolField(value: _storage._validateAccountWithMobileDone, fieldNumber: 5)
      }
      if !_storage._validateAccountWithMobileMessage.isEmpty {
        try visitor.visitSingularStringField(value: _storage._validateAccountWithMobileMessage, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Identity_Account_ValidateAccountWithMobileResponse, rhs: Elint_Services_Product_Identity_Account_ValidateAccountWithMobileResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._accountCreationAuthDetails != rhs_storage._accountCreationAuthDetails {return false}
        if _storage._accountExistsWithMobile != rhs_storage._accountExistsWithMobile {return false}
        if _storage._verificationCodeTokenDetails != rhs_storage._verificationCodeTokenDetails {return false}
        if _storage._codeSentAt != rhs_storage._codeSentAt {return false}
        if _storage._validateAccountWithMobileDone != rhs_storage._validateAccountWithMobileDone {return false}
        if _storage._validateAccountWithMobileMessage != rhs_storage._validateAccountWithMobileMessage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Elint_Services_Product_Identity_Account_VerificationAccountRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".VerificationAccountRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "account_creation_auth_details"),
    2: .standard(proto: "resend_code"),
    3: .standard(proto: "verification_code"),
    4: .standard(proto: "verification_code_token_details"),
    5: .standard(proto: "requested_at"),
  ]

  fileprivate class _StorageClass {
    var _accountCreationAuthDetails: Elint_Services_Product_Identity_Account_AccountCreationAuthDetails? = nil
    var _resendCode: Bool = false
    var _verificationCode: String = String()
    var _verificationCodeTokenDetails: Elint_Entity_TemporaryTokenDetails? = nil
    var _requestedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _accountCreationAuthDetails = source._accountCreationAuthDetails
      _resendCode = source._resendCode
      _verificationCode = source._verificationCode
      _verificationCodeTokenDetails = source._verificationCodeTokenDetails
      _requestedAt = source._requestedAt
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._accountCreationAuthDetails) }()
        case 2: try { try decoder.decodeSingularBoolField(value: &_storage._resendCode) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._verificationCode) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._verificationCodeTokenDetails) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._requestedAt) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._accountCreationAuthDetails {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if _storage._resendCode != false {
        try visitor.visitSingularBoolField(value: _storage._resendCode, fieldNumber: 2)
      }
      if !_storage._verificationCode.isEmpty {
        try visitor.visitSingularStringField(value: _storage._verificationCode, fieldNumber: 3)
      }
      if let v = _storage._verificationCodeTokenDetails {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if let v = _storage._requestedAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Identity_Account_VerificationAccountRequest, rhs: Elint_Services_Product_Identity_Account_VerificationAccountRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._accountCreationAuthDetails != rhs_storage._accountCreationAuthDetails {return false}
        if _storage._resendCode != rhs_storage._resendCode {return false}
        if _storage._verificationCode != rhs_storage._verificationCode {return false}
        if _storage._verificationCodeTokenDetails != rhs_storage._verificationCodeTokenDetails {return false}
        if _storage._requestedAt != rhs_storage._requestedAt {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Elint_Services_Product_Identity_Account_VerificationAccountResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".VerificationAccountResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "verification_done"),
    2: .standard(proto: "verification_message"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.verificationDone) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.verificationMessage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.verificationDone != false {
      try visitor.visitSingularBoolField(value: self.verificationDone, fieldNumber: 1)
    }
    if !self.verificationMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.verificationMessage, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Identity_Account_VerificationAccountResponse, rhs: Elint_Services_Product_Identity_Account_VerificationAccountResponse) -> Bool {
    if lhs.verificationDone != rhs.verificationDone {return false}
    if lhs.verificationMessage != rhs.verificationMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Elint_Services_Product_Identity_Account_CaptureAccountMetaDetailsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CaptureAccountMetaDetailsRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "account_creation_auth_details"),
    2: .standard(proto: "account_first_name"),
    3: .standard(proto: "account_last_name"),
    4: .standard(proto: "account_birth_at"),
    5: .standard(proto: "account_gender"),
    6: .standard(proto: "requested_at"),
  ]

  fileprivate class _StorageClass {
    var _accountCreationAuthDetails: Elint_Services_Product_Identity_Account_AccountCreationAuthDetails? = nil
    var _accountFirstName: String = String()
    var _accountLastName: String = String()
    var _accountBirthAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _accountGender: Elint_Entity_AccountGender = .unknown
    var _requestedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _accountCreationAuthDetails = source._accountCreationAuthDetails
      _accountFirstName = source._accountFirstName
      _accountLastName = source._accountLastName
      _accountBirthAt = source._accountBirthAt
      _accountGender = source._accountGender
      _requestedAt = source._requestedAt
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._accountCreationAuthDetails) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._accountFirstName) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._accountLastName) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._accountBirthAt) }()
        case 5: try { try decoder.decodeSingularEnumField(value: &_storage._accountGender) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._requestedAt) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._accountCreationAuthDetails {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if !_storage._accountFirstName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._accountFirstName, fieldNumber: 2)
      }
      if !_storage._accountLastName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._accountLastName, fieldNumber: 3)
      }
      if let v = _storage._accountBirthAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if _storage._accountGender != .unknown {
        try visitor.visitSingularEnumField(value: _storage._accountGender, fieldNumber: 5)
      }
      if let v = _storage._requestedAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Identity_Account_CaptureAccountMetaDetailsRequest, rhs: Elint_Services_Product_Identity_Account_CaptureAccountMetaDetailsRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._accountCreationAuthDetails != rhs_storage._accountCreationAuthDetails {return false}
        if _storage._accountFirstName != rhs_storage._accountFirstName {return false}
        if _storage._accountLastName != rhs_storage._accountLastName {return false}
        if _storage._accountBirthAt != rhs_storage._accountBirthAt {return false}
        if _storage._accountGender != rhs_storage._accountGender {return false}
        if _storage._requestedAt != rhs_storage._requestedAt {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Elint_Services_Product_Identity_Account_CaptureAccountMetaDetailsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CaptureAccountMetaDetailsResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "account_service_access_auth_details"),
    2: .standard(proto: "account_creation_done"),
    3: .standard(proto: "account_creation_message"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._accountServiceAccessAuthDetails) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.accountCreationDone) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accountCreationMessage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._accountServiceAccessAuthDetails {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if self.accountCreationDone != false {
      try visitor.visitSingularBoolField(value: self.accountCreationDone, fieldNumber: 2)
    }
    if !self.accountCreationMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.accountCreationMessage, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Identity_Account_CaptureAccountMetaDetailsResponse, rhs: Elint_Services_Product_Identity_Account_CaptureAccountMetaDetailsResponse) -> Bool {
    if lhs._accountServiceAccessAuthDetails != rhs._accountServiceAccessAuthDetails {return false}
    if lhs.accountCreationDone != rhs.accountCreationDone {return false}
    if lhs.accountCreationMessage != rhs.accountCreationMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Elint_Services_Product_Identity_Account_AccountCreationAuthDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AccountCreationAuthDetails"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "account_mobile_number"),
    2: .standard(proto: "account_creation_session_token_details"),
    3: .standard(proto: "requested_at"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.accountMobileNumber) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._accountCreationSessionTokenDetails) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._requestedAt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.accountMobileNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.accountMobileNumber, fieldNumber: 1)
    }
    if let v = self._accountCreationSessionTokenDetails {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    if let v = self._requestedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Identity_Account_AccountCreationAuthDetails, rhs: Elint_Services_Product_Identity_Account_AccountCreationAuthDetails) -> Bool {
    if lhs.accountMobileNumber != rhs.accountMobileNumber {return false}
    if lhs._accountCreationSessionTokenDetails != rhs._accountCreationSessionTokenDetails {return false}
    if lhs._requestedAt != rhs._requestedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
