//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ethos/elint/services/product/identity/account/space_gateway_account.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Elint_Services_Product_Identity_SpaceGatewayAccountServiceClient`, then call methods of this protocol to make API calls.
internal protocol Elint_Services_Product_Identity_SpaceGatewayAccountServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Elint_Services_Product_Identity_SpaceGatewayAccountServiceClientInterceptorFactoryProtocol? { get }

  func spaceGatewayAccess(
    _ request: Elint_Services_Product_Identity_SpaceGatewayAccessRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Elint_Services_Product_Identity_SpaceGatewayAccessRequest, Elint_Services_Product_Identity_SpaceGatewayAccessResponse>
}

extension Elint_Services_Product_Identity_SpaceGatewayAccountServiceClientProtocol {
  internal var serviceName: String {
    return "elint.services.product.identity.SpaceGatewayAccountService"
  }

  /// Unary call to SpaceGatewayAccess
  ///
  /// - Parameters:
  ///   - request: Request to send to SpaceGatewayAccess.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func spaceGatewayAccess(
    _ request: Elint_Services_Product_Identity_SpaceGatewayAccessRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Elint_Services_Product_Identity_SpaceGatewayAccessRequest, Elint_Services_Product_Identity_SpaceGatewayAccessResponse> {
    return self.makeUnaryCall(
      path: "/elint.services.product.identity.SpaceGatewayAccountService/SpaceGatewayAccess",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSpaceGatewayAccessInterceptors() ?? []
    )
  }
}

internal protocol Elint_Services_Product_Identity_SpaceGatewayAccountServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'spaceGatewayAccess'.
  func makeSpaceGatewayAccessInterceptors() -> [ClientInterceptor<Elint_Services_Product_Identity_SpaceGatewayAccessRequest, Elint_Services_Product_Identity_SpaceGatewayAccessResponse>]
}

internal final class Elint_Services_Product_Identity_SpaceGatewayAccountServiceClient: Elint_Services_Product_Identity_SpaceGatewayAccountServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Elint_Services_Product_Identity_SpaceGatewayAccountServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the elint.services.product.identity.SpaceGatewayAccountService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Elint_Services_Product_Identity_SpaceGatewayAccountServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

