// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ethos/elint/entities/file_page.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Elint_Entity_FilePage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileDetails: Elint_Entity_SpaceKnowledgeDomainFile {
    get {return _fileDetails ?? Elint_Entity_SpaceKnowledgeDomainFile()}
    set {_fileDetails = newValue}
  }
  /// Returns true if `fileDetails` has been explicitly set.
  var hasFileDetails: Bool {return self._fileDetails != nil}
  /// Clears the value of `fileDetails`. Subsequent reads from it will return its default value.
  mutating func clearFileDetails() {self._fileDetails = nil}

  var pageID: String = String()

  var pageNumber: String = String()

  var pageExtensionType: Elint_Entity_ExtentionType = .png

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _fileDetails: Elint_Entity_SpaceKnowledgeDomainFile? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "elint.entity"

extension Elint_Entity_FilePage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FilePage"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "file_details"),
    2: .standard(proto: "page_id"),
    3: .standard(proto: "page_number"),
    4: .standard(proto: "page_extension_type"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._fileDetails) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.pageID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.pageNumber) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.pageExtensionType) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._fileDetails {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.pageID.isEmpty {
      try visitor.visitSingularStringField(value: self.pageID, fieldNumber: 2)
    }
    if !self.pageNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.pageNumber, fieldNumber: 3)
    }
    if self.pageExtensionType != .png {
      try visitor.visitSingularEnumField(value: self.pageExtensionType, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Entity_FilePage, rhs: Elint_Entity_FilePage) -> Bool {
    if lhs._fileDetails != rhs._fileDetails {return false}
    if lhs.pageID != rhs.pageID {return false}
    if lhs.pageNumber != rhs.pageNumber {return false}
    if lhs.pageExtensionType != rhs.pageExtensionType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
