// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ethos/elint/entities/knowledge_domain.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Elint_Entity_KnowledgeDomain {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var knowledgeDomainID: String = String()

  var knowledgeDomainName: String = String()

  var knowledgeDomainColor: String = String()

  var createdAt: String = String()

  var lastUpdatedAt: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "elint.entity"

extension Elint_Entity_KnowledgeDomain: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".KnowledgeDomain"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "knowledge_domain_id"),
    2: .standard(proto: "knowledge_domain_name"),
    3: .standard(proto: "knowledge_domain_color"),
    4: .standard(proto: "created_at"),
    5: .standard(proto: "last_updated_at"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.knowledgeDomainID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.knowledgeDomainName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.knowledgeDomainColor) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.createdAt) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.lastUpdatedAt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.knowledgeDomainID.isEmpty {
      try visitor.visitSingularStringField(value: self.knowledgeDomainID, fieldNumber: 1)
    }
    if !self.knowledgeDomainName.isEmpty {
      try visitor.visitSingularStringField(value: self.knowledgeDomainName, fieldNumber: 2)
    }
    if !self.knowledgeDomainColor.isEmpty {
      try visitor.visitSingularStringField(value: self.knowledgeDomainColor, fieldNumber: 3)
    }
    if !self.createdAt.isEmpty {
      try visitor.visitSingularStringField(value: self.createdAt, fieldNumber: 4)
    }
    if !self.lastUpdatedAt.isEmpty {
      try visitor.visitSingularStringField(value: self.lastUpdatedAt, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Entity_KnowledgeDomain, rhs: Elint_Entity_KnowledgeDomain) -> Bool {
    if lhs.knowledgeDomainID != rhs.knowledgeDomainID {return false}
    if lhs.knowledgeDomainName != rhs.knowledgeDomainName {return false}
    if lhs.knowledgeDomainColor != rhs.knowledgeDomainColor {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.lastUpdatedAt != rhs.lastUpdatedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
