//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ethos/elint/services/product/identity/organisation/onboard_organization_space.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Elint_Services_Product_Identity_OnboardOrganizationSpaceServiceClient`, then call methods of this protocol to make API calls.
internal protocol Elint_Services_Product_Identity_OnboardOrganizationSpaceServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Elint_Services_Product_Identity_OnboardOrganizationSpaceServiceClientInterceptorFactoryProtocol? { get }

  func claim_organization_space(
    _ request: Elint_Entity_ClaimOrganizationSpaceRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Elint_Entity_ClaimOrganizationSpaceRequest, Elint_Entity_ClaimOrganizationSpaceResponse>
}

extension Elint_Services_Product_Identity_OnboardOrganizationSpaceServiceClientProtocol {
  internal var serviceName: String {
    return "elint.services.product.identity.OnboardOrganizationSpaceService"
  }

  /// Unary call to claim_organization_space
  ///
  /// - Parameters:
  ///   - request: Request to send to claim_organization_space.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func claim_organization_space(
    _ request: Elint_Entity_ClaimOrganizationSpaceRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Elint_Entity_ClaimOrganizationSpaceRequest, Elint_Entity_ClaimOrganizationSpaceResponse> {
    return self.makeUnaryCall(
      path: "/elint.services.product.identity.OnboardOrganizationSpaceService/claim_organization_space",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeclaim_organization_spaceInterceptors() ?? []
    )
  }
}

internal protocol Elint_Services_Product_Identity_OnboardOrganizationSpaceServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'claim_organization_space'.
  func makeclaim_organization_spaceInterceptors() -> [ClientInterceptor<Elint_Entity_ClaimOrganizationSpaceRequest, Elint_Entity_ClaimOrganizationSpaceResponse>]
}

internal final class Elint_Services_Product_Identity_OnboardOrganizationSpaceServiceClient: Elint_Services_Product_Identity_OnboardOrganizationSpaceServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Elint_Services_Product_Identity_OnboardOrganizationSpaceServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the elint.services.product.identity.OnboardOrganizationSpaceService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Elint_Services_Product_Identity_OnboardOrganizationSpaceServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

