//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ethos/elint/services/product/knowledge/space_knowledge_domain_file/access_space_knowledge_domain_file.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Service Definitions
///
/// Usage: instantiate `Elint_Services_Product_Knowledge_File_AccessSpaceKnowledgeDomainFileServiceClient`, then call methods of this protocol to make API calls.
internal protocol Elint_Services_Product_Knowledge_File_AccessSpaceKnowledgeDomainFileServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Elint_Services_Product_Knowledge_File_AccessSpaceKnowledgeDomainFileServiceClientInterceptorFactoryProtocol? { get }

  func accessSpaceKnowledgeDomainFileToken(
    _ request: Elint_Services_Product_Knowledge_Domain_SpaceKnowledgeDomainServicesAccessAuthDetails,
    callOptions: CallOptions?
  ) -> UnaryCall<Elint_Services_Product_Knowledge_Domain_SpaceKnowledgeDomainServicesAccessAuthDetails, Elint_Services_Product_Knowledge_File_SpaceKnowledgeDomainFileServicesAccessAuthDetails>
}

extension Elint_Services_Product_Knowledge_File_AccessSpaceKnowledgeDomainFileServiceClientProtocol {
  internal var serviceName: String {
    return "elint.services.product.knowledge.file.AccessSpaceKnowledgeDomainFileService"
  }

  /// Unary call to AccessSpaceKnowledgeDomainFileToken
  ///
  /// - Parameters:
  ///   - request: Request to send to AccessSpaceKnowledgeDomainFileToken.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func accessSpaceKnowledgeDomainFileToken(
    _ request: Elint_Services_Product_Knowledge_Domain_SpaceKnowledgeDomainServicesAccessAuthDetails,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Elint_Services_Product_Knowledge_Domain_SpaceKnowledgeDomainServicesAccessAuthDetails, Elint_Services_Product_Knowledge_File_SpaceKnowledgeDomainFileServicesAccessAuthDetails> {
    return self.makeUnaryCall(
      path: "/elint.services.product.knowledge.file.AccessSpaceKnowledgeDomainFileService/AccessSpaceKnowledgeDomainFileToken",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAccessSpaceKnowledgeDomainFileTokenInterceptors() ?? []
    )
  }
}

internal protocol Elint_Services_Product_Knowledge_File_AccessSpaceKnowledgeDomainFileServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'accessSpaceKnowledgeDomainFileToken'.
  func makeAccessSpaceKnowledgeDomainFileTokenInterceptors() -> [ClientInterceptor<Elint_Services_Product_Knowledge_Domain_SpaceKnowledgeDomainServicesAccessAuthDetails, Elint_Services_Product_Knowledge_File_SpaceKnowledgeDomainFileServicesAccessAuthDetails>]
}

internal final class Elint_Services_Product_Knowledge_File_AccessSpaceKnowledgeDomainFileServiceClient: Elint_Services_Product_Knowledge_File_AccessSpaceKnowledgeDomainFileServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Elint_Services_Product_Knowledge_File_AccessSpaceKnowledgeDomainFileServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the elint.services.product.knowledge.file.AccessSpaceKnowledgeDomainFileService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Elint_Services_Product_Knowledge_File_AccessSpaceKnowledgeDomainFileServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

