//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ethos/elint/services/product/knowledge/space_knowledge_domain_file/create_space_knowledge_domain_file.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Service Definitions
///
/// Usage: instantiate `Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileServiceClient`, then call methods of this protocol to make API calls.
internal protocol Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileServiceClientInterceptorFactoryProtocol? { get }

  func createSpaceKnowledgeDomainFile(
    _ request: Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileRequest, Elint_Entity_SpaceKnowledgeDomainFile>

  func uploadSpaceKnowledgeDomainFile(
    callOptions: CallOptions?,
    handler: @escaping (Elint_Services_Product_Knowledge_File_UploadSpaceKnowledgeDomainFileResponse) -> Void
  ) -> BidirectionalStreamingCall<Elint_Services_Product_Knowledge_File_UploadSpaceKnowledgeDomainFileRequest, Elint_Services_Product_Knowledge_File_UploadSpaceKnowledgeDomainFileResponse>
}

extension Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileServiceClientProtocol {
  internal var serviceName: String {
    return "elint.services.product.knowledge.file.CreateSpaceKnowledgeDomainFileService"
  }

  /// Unary call to CreateSpaceKnowledgeDomainFile
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateSpaceKnowledgeDomainFile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createSpaceKnowledgeDomainFile(
    _ request: Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileRequest, Elint_Entity_SpaceKnowledgeDomainFile> {
    return self.makeUnaryCall(
      path: "/elint.services.product.knowledge.file.CreateSpaceKnowledgeDomainFileService/CreateSpaceKnowledgeDomainFile",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateSpaceKnowledgeDomainFileInterceptors() ?? []
    )
  }

  /// Bidirectional streaming call to UploadSpaceKnowledgeDomainFile
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  internal func uploadSpaceKnowledgeDomainFile(
    callOptions: CallOptions? = nil,
    handler: @escaping (Elint_Services_Product_Knowledge_File_UploadSpaceKnowledgeDomainFileResponse) -> Void
  ) -> BidirectionalStreamingCall<Elint_Services_Product_Knowledge_File_UploadSpaceKnowledgeDomainFileRequest, Elint_Services_Product_Knowledge_File_UploadSpaceKnowledgeDomainFileResponse> {
    return self.makeBidirectionalStreamingCall(
      path: "/elint.services.product.knowledge.file.CreateSpaceKnowledgeDomainFileService/UploadSpaceKnowledgeDomainFile",
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUploadSpaceKnowledgeDomainFileInterceptors() ?? [],
      handler: handler
    )
  }
}

internal protocol Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'createSpaceKnowledgeDomainFile'.
  func makeCreateSpaceKnowledgeDomainFileInterceptors() -> [ClientInterceptor<Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileRequest, Elint_Entity_SpaceKnowledgeDomainFile>]

  /// - Returns: Interceptors to use when invoking 'uploadSpaceKnowledgeDomainFile'.
  func makeUploadSpaceKnowledgeDomainFileInterceptors() -> [ClientInterceptor<Elint_Services_Product_Knowledge_File_UploadSpaceKnowledgeDomainFileRequest, Elint_Services_Product_Knowledge_File_UploadSpaceKnowledgeDomainFileResponse>]
}

internal final class Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileServiceClient: Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the elint.services.product.knowledge.file.CreateSpaceKnowledgeDomainFileService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Elint_Services_Product_Knowledge_File_CreateSpaceKnowledgeDomainFileServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

