//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ethos/elint/services/product/knowledge/space_knowledge_domain_file/discover_space_knowledge_domain_file.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Elint_Services_Product_Knowledge_File_DiscoverKnowledgeDomainFileServiceClient`, then call methods of this protocol to make API calls.
internal protocol Elint_Services_Product_Knowledge_File_DiscoverKnowledgeDomainFileServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Elint_Services_Product_Knowledge_File_DiscoverKnowledgeDomainFileServiceClientInterceptorFactoryProtocol? { get }

  func getFileDetails(
    _ request: Elint_Services_Product_Knowledge_File_GetFileDetailsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Elint_Services_Product_Knowledge_File_GetFileDetailsRequest, Elint_Entity_SpaceKnowledgeDomainFile>

  func fileExistsByID(
    _ request: Elint_Services_Product_Knowledge_File_FileExistsByIDRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Elint_Services_Product_Knowledge_File_FileExistsByIDRequest, Elint_Services_Product_Knowledge_File_FileExistsByIDResponse>
}

extension Elint_Services_Product_Knowledge_File_DiscoverKnowledgeDomainFileServiceClientProtocol {
  internal var serviceName: String {
    return "elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService"
  }

  /// Unary call to GetFileDetails
  ///
  /// - Parameters:
  ///   - request: Request to send to GetFileDetails.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getFileDetails(
    _ request: Elint_Services_Product_Knowledge_File_GetFileDetailsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Elint_Services_Product_Knowledge_File_GetFileDetailsRequest, Elint_Entity_SpaceKnowledgeDomainFile> {
    return self.makeUnaryCall(
      path: "/elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService/GetFileDetails",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFileDetailsInterceptors() ?? []
    )
  }

  /// Unary call to FileExistsByID
  ///
  /// - Parameters:
  ///   - request: Request to send to FileExistsByID.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func fileExistsByID(
    _ request: Elint_Services_Product_Knowledge_File_FileExistsByIDRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Elint_Services_Product_Knowledge_File_FileExistsByIDRequest, Elint_Services_Product_Knowledge_File_FileExistsByIDResponse> {
    return self.makeUnaryCall(
      path: "/elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService/FileExistsByID",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFileExistsByIDInterceptors() ?? []
    )
  }
}

internal protocol Elint_Services_Product_Knowledge_File_DiscoverKnowledgeDomainFileServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'getFileDetails'.
  func makeGetFileDetailsInterceptors() -> [ClientInterceptor<Elint_Services_Product_Knowledge_File_GetFileDetailsRequest, Elint_Entity_SpaceKnowledgeDomainFile>]

  /// - Returns: Interceptors to use when invoking 'fileExistsByID'.
  func makeFileExistsByIDInterceptors() -> [ClientInterceptor<Elint_Services_Product_Knowledge_File_FileExistsByIDRequest, Elint_Services_Product_Knowledge_File_FileExistsByIDResponse>]
}

internal final class Elint_Services_Product_Knowledge_File_DiscoverKnowledgeDomainFileServiceClient: Elint_Services_Product_Knowledge_File_DiscoverKnowledgeDomainFileServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Elint_Services_Product_Knowledge_File_DiscoverKnowledgeDomainFileServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Elint_Services_Product_Knowledge_File_DiscoverKnowledgeDomainFileServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

