// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ethos/elint/services/product/knowledge/space_knowledge_domain_file/discover_space_knowledge_domain_file.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Elint_Services_Product_Knowledge_File_GetFileDetailsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var accountKnowledgeDomainFileAccessMeta: Elint_Entity_AccountSpaceKnowledgeDomainFileAccessMeta {
    get {return _accountKnowledgeDomainFileAccessMeta ?? Elint_Entity_AccountSpaceKnowledgeDomainFileAccessMeta()}
    set {_accountKnowledgeDomainFileAccessMeta = newValue}
  }
  /// Returns true if `accountKnowledgeDomainFileAccessMeta` has been explicitly set.
  var hasAccountKnowledgeDomainFileAccessMeta: Bool {return self._accountKnowledgeDomainFileAccessMeta != nil}
  /// Clears the value of `accountKnowledgeDomainFileAccessMeta`. Subsequent reads from it will return its default value.
  mutating func clearAccountKnowledgeDomainFileAccessMeta() {self._accountKnowledgeDomainFileAccessMeta = nil}

  var fileID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _accountKnowledgeDomainFileAccessMeta: Elint_Entity_AccountSpaceKnowledgeDomainFileAccessMeta? = nil
}

struct Elint_Services_Product_Knowledge_File_FileExistsByIDRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var accountKnowledgeDomainFileAccessMeta: Elint_Entity_AccountSpaceKnowledgeDomainFileAccessMeta {
    get {return _accountKnowledgeDomainFileAccessMeta ?? Elint_Entity_AccountSpaceKnowledgeDomainFileAccessMeta()}
    set {_accountKnowledgeDomainFileAccessMeta = newValue}
  }
  /// Returns true if `accountKnowledgeDomainFileAccessMeta` has been explicitly set.
  var hasAccountKnowledgeDomainFileAccessMeta: Bool {return self._accountKnowledgeDomainFileAccessMeta != nil}
  /// Clears the value of `accountKnowledgeDomainFileAccessMeta`. Subsequent reads from it will return its default value.
  mutating func clearAccountKnowledgeDomainFileAccessMeta() {self._accountKnowledgeDomainFileAccessMeta = nil}

  var fileID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _accountKnowledgeDomainFileAccessMeta: Elint_Entity_AccountSpaceKnowledgeDomainFileAccessMeta? = nil
}

struct Elint_Services_Product_Knowledge_File_FileExistsByIDResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileExists: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "elint.services.product.knowledge.file"

extension Elint_Services_Product_Knowledge_File_GetFileDetailsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetFileDetailsRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "account_knowledge_domain_file_access_meta"),
    2: .standard(proto: "file_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._accountKnowledgeDomainFileAccessMeta) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fileID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._accountKnowledgeDomainFileAccessMeta {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.fileID.isEmpty {
      try visitor.visitSingularStringField(value: self.fileID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Knowledge_File_GetFileDetailsRequest, rhs: Elint_Services_Product_Knowledge_File_GetFileDetailsRequest) -> Bool {
    if lhs._accountKnowledgeDomainFileAccessMeta != rhs._accountKnowledgeDomainFileAccessMeta {return false}
    if lhs.fileID != rhs.fileID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Elint_Services_Product_Knowledge_File_FileExistsByIDRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FileExistsByIDRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "account_knowledge_domain_file_access_meta"),
    2: .standard(proto: "file_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._accountKnowledgeDomainFileAccessMeta) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fileID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._accountKnowledgeDomainFileAccessMeta {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.fileID.isEmpty {
      try visitor.visitSingularStringField(value: self.fileID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Knowledge_File_FileExistsByIDRequest, rhs: Elint_Services_Product_Knowledge_File_FileExistsByIDRequest) -> Bool {
    if lhs._accountKnowledgeDomainFileAccessMeta != rhs._accountKnowledgeDomainFileAccessMeta {return false}
    if lhs.fileID != rhs.fileID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Elint_Services_Product_Knowledge_File_FileExistsByIDResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FileExistsByIDResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "file_exists"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.fileExists) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.fileExists != false {
      try visitor.visitSingularBoolField(value: self.fileExists, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Elint_Services_Product_Knowledge_File_FileExistsByIDResponse, rhs: Elint_Services_Product_Knowledge_File_FileExistsByIDResponse) -> Bool {
    if lhs.fileExists != rhs.fileExists {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
