//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ethos/elint/services/product/knowledge/data_service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Elint_Services_Product_Knowledge_FileUploadServiceClient`, then call methods of this protocol to make API calls.
internal protocol Elint_Services_Product_Knowledge_FileUploadServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Elint_Services_Product_Knowledge_FileUploadServiceClientInterceptorFactoryProtocol? { get }

  func fileUpload(
    callOptions: CallOptions?
  ) -> ClientStreamingCall<Elint_Services_Product_Knowledge_FileUploadRequest, Elint_Services_Product_Knowledge_FileUploadResponse>
}

extension Elint_Services_Product_Knowledge_FileUploadServiceClientProtocol {
  internal var serviceName: String {
    return "elint.services.product.knowledge.FileUploadService"
  }

  /// Client streaming call to FileUpload
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata, status and response.
  internal func fileUpload(
    callOptions: CallOptions? = nil
  ) -> ClientStreamingCall<Elint_Services_Product_Knowledge_FileUploadRequest, Elint_Services_Product_Knowledge_FileUploadResponse> {
    return self.makeClientStreamingCall(
      path: "/elint.services.product.knowledge.FileUploadService/FileUpload",
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFileUploadInterceptors() ?? []
    )
  }
}

internal protocol Elint_Services_Product_Knowledge_FileUploadServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'fileUpload'.
  func makeFileUploadInterceptors() -> [ClientInterceptor<Elint_Services_Product_Knowledge_FileUploadRequest, Elint_Services_Product_Knowledge_FileUploadResponse>]
}

internal final class Elint_Services_Product_Knowledge_FileUploadServiceClient: Elint_Services_Product_Knowledge_FileUploadServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Elint_Services_Product_Knowledge_FileUploadServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the elint.services.product.knowledge.FileUploadService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Elint_Services_Product_Knowledge_FileUploadServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

